FROM debian:8

{% include "roles/common/templates/Dockerfile.j2" %}

ENV CONFLUENCE_VERSION={{ version }}

RUN mkdir -p /opt/confluence && \
  cd /opt/confluence && \
  wget -nv https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-${CONFLUENCE_VERSION}.tar.gz && \
  tar xf atlassian-confluence-${CONFLUENCE_VERSION}.tar.gz && \
  mv atlassian-confluence-${CONFLUENCE_VERSION} install && \
  rm -f atlassian-confluence-${CONFLUENCE_VERSION}.tar.gz

RUN wget -nv {{ mysql_connector }} -P /opt/confluence/install/lib

VOLUME /opt/confluence/data /opt/confluence/install/logs
COPY config/ /opt/confluence/config/
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
RUN adduser -h /opt/confluence/data -D confluence
{% if version|version_compare("6.0.0", ">=") %}
RUN apt update
RUN apt-get install apache2 apache2-doc apache2-utils -y
mkdir -p /run/apache2
COPY apache2.conf /etc/apache2/conf-enabled/default.conf
RUN sed -i -e 's/Listen 80/Listen 8090/g' /etc/apache2/apache2.conf
RUN sed -i -e 's/8090/8092/g' /opt/confluence/install/conf/server.xml
{% endif %}
EXPOSE 8090

CMD /opt/confluence/install/bin/start-confluence.sh -fg

# Running modifications
RUN sed -i -e 's$date +%F_%T$date +%F_%H%M%S$g' /opt/confluence/install/bin/setenv.sh && \
  echo "" >> /opt/confluence/install/confluence/WEB-INF/classes/confluence-init.properties && \
  echo "confluence.home=/opt/confluence/data" >> /opt/confluence/install/confluence/WEB-INF/classes/confluence-init.properties && \
  echo "load /opt/confluence/install/lib/*.jar" >> /usr/groovy/conf/groovy-starter.conf && \
  echo "load /opt/confluence/install/confluence/WEB-INF/lib/*.jar" >> /usr/groovy/conf/groovy-starter.conf
