version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy
  jiradb:
    image: atlassian/postgres:9.4
    volumes:
      - jiradb:/var/lib/postgresql/data
    environment:
      - DB_PASS=atlassian
      - DB_NAME=jira
      - DB_USER=atlassian
    networks:
      - jira
  confluencedb:
    image: atlassian/postgres:9.4
    volumes:
      - confluencedb:/var/lib/postgresql/data
    environment:
      - DB_PASS=atlassian
      - DB_NAME=confluence
      - DB_USER=atlassian
    networks:
      - confluence
  # bitbucketdb:
  #   image: atlassian/postgres:9.4
  #   volumes:
  #     - bitbucketdb:/var/lib/postgresql/data
  #   environment:
  #     - DB_PASS=atlassian
  #     - DB_NAME=bitbucket
  #     - DB_USER=atlassian
  #   networks:
  #     - bitbucket
  jira:
    image: atlassian/jira:7.3.8
    volumes:
      - jiradata:/opt/jira/data
      #- ./jira.config:/opt/jira/config/jira.config
    networks:
      - jira
      - proxy
    environment:
      - VIRTUAL_HOST=jira.intranet.local
      - VIRTUAL_PORT=8080
  confluence:
    image: atlassian/confluence:6.2.3
    volumes:
      - confluencedata:/opt/confluence/data
      #- ./confluence.config:/opt/confluence/config/confluence.config
    networks:
      - confluence
      - proxy
    environment:
      - VIRTUAL_HOST=confluence.intranet.local
      - VIRTUAL_PORT=8090
  # bitbucket:
  #   image: atlassian/bitbucket:5.1.0
  #   volumes:
  #     - bitbucketdata:/opt/bitbucket/data
  #     #- ./bitbucket.config:/opt/bitbucket/config/bitbucket.config
  #   networks:
  #     - bitbucket
  #     - proxy
  #   ports:
  #     - 0.0.0.0:7999:7999
  #   environment:
  #     - VIRTUAL_HOST=bitbucket.intranet.local
  #     - VIRTUAL_PORT=7990

volumes:
  jiradb:
  jiradata:
  confluencedb:
  confluencedata:
  # bitbucketdb:
  # bitbucketdata:

networks:
  jira:
  confluence:
  # bitbucket:
  proxy:
