FROM {% if registry is defined %}{{ registry }}/{% endif %}{{ image_base }}/application:{{ java }}

{% include "roles/common/templates/Dockerfile.j2" %}

ENV BAMBOO_VERSION={{ version }}
ENV BAMBOO_AGENT_HOME /opt/bamboo-agent/data/

## MAVEN INSTALLATION
RUN mkdir -p /opt \
  cd /opt \
  && wget -nv https://archive.apache.org/dist/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.tar.gz \
  && tar xf apache-maven-3.3.1-bin.tar.gz \
  && rm -rf apache-maven-3.3.1-bin.tar.gz
RUN ln -sf /opt/apache-maven-3.3.1/bin/mvn /usr/bin/mvn; ln -sf /opt/apache-maven-3.3.1/bin/mvnDebug /usr/bin/mvnDebug

# to map an artifactory, must be in entrypoint
# COPY settings.xml /opt/apache-maven-3.3.1/conf/

RUN mkdir -p /opt/bamboo-agent/
RUN adduser -D -h $BAMBOO_AGENT_HOME bamboo
RUN chown -R bamboo:bamboo /opt

USER bamboo
VOLUME /opt/bamboo-agent/data/

## BAMBOO REMOTE INSTALLATION
CMD cd $BAMBOO_AGENT_HOME && wget -nv $BAMBOO_SERVER_URL/agentServer/agentInstaller/atlassian-bamboo-agent-installer-$BAMBOO_VERSION.jar -O atlassian-bamboo-agent-installer.jar -o install.txt && java -Dbamboo.home=$BAMBOO_AGENT_HOME -jar atlassian-bamboo-agent-installer.jar $BAMBOO_SERVER_URL/agentServer/
