FROM {{ os }}:{{ osversion }}

{% include "roles/common/templates/Dockerfile.j2" %}

RUN apk add --no-cache \
      bash \
      curl \
      less \
      procps \
      rsync \
      tar \
      unzip \
      wget \
      zip \
      openssh \
      tzdata

RUN ln -sf /usr/share/zoneinfo/Europe/Brussels /etc/localtime

## UTF-8
ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \ 
    LANGUAGE=en_US.UTF-8 \
    TERM=linux
#RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8

{# Fetch gosu, allow applications to run as non-user #}
RUN curl -o /usr/local/bin/gosu -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-amd64" \
  && chmod +x /usr/local/bin/gosu
